### ISSUE TITLE
Execution/installation fail in Fedora 41

### ISSUE THREAD

**Issue by kotlasu** [Ultramarine-Linux/hop#1]
Hi,
I've installed dependencies and nim mentioned in readme but I get following error while trying to install hop:
> ┌─ Fail to execute command: nimble build --define:releasever=41 --verbose
┊      Info:  Nimble data file "/root/.nimble/nimbledata2.json" has been loaded.
┊ packageparser.nim(326)   readPackageInfo
┊ 
┊     Error:  Could not read package info file in /home/kaczuszka/Downloads/hop-master/umswitch.nimble;
┊         ...   Reading as ini file failed with: 
┊         ...     Invalid section: .
┊         ...   Evaluating as NimScript file failed with: 
┊         ...     /home/kaczuszka/Downloads/hop-master/umswitch.nimble(11, 21) Error: cannot open file: nimsutils/src/nimsutils
┊         ... printPkgInfo() failed.
┊      Info:  Nimble data file "/root/.nimble/nimbledata2.json" has been saved.
└─ Command returned exit code 1

It's probably a "me" problem (a.k.a. skill issue) but it's worth to report anyway ;D

**Comment by madonuko** [comment]
It seems to be saying `nimsutils/src/nimsutils` is not found. Did you also clone that folder?

**Comment by kotlasu** [comment]
Thanks for pointing this out! Of course it was a "me problem" - I downloaded the code instead of doing a git clone/git pull.
nimutils are in a different repo, that's why it wasn't working. I've added it to a correct folder and now it works as a charm.

Thanks for creating this app - I have no idea why I can't use "dnf groupinstall" or "dnf install @" in Ultramarine [like in Fedora](https://docs.fedoraproject.org/en-US/quick-docs/switching-desktop-environments/) but thanks to you I can add/swap desktop environment without reinstalling whole OS.

**Comment by madonuko** [comment]
> I have no idea why I can't use "dnf groupinstall" or "dnf install @" in Ultramarine

Supposedly you can (that's actually what the app basically does)

Also you know… this app is available in the Ultramarine repositories already via `dnf install hop`
